// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxozchwpuwowlsurmptr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4b3pjaHdwdXdvd2xzdXJtcHRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2OTkwMDAsImV4cCI6MjA1OTI3NTAwMH0.43QPJjgs3KSuZU9tDovPCabticNYympWQbeeckfnvnE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);